### PR TITLE
Add conda packaging

### PR DESCRIPTION
**Pull request by ScottWales**
Add packaging so ncimonitor can be added to conda environments

### CODE REVIEW

**Comment by aidanheerdegen** [comment]
Thanks for that @ScottWales. It was on my to-do list for conda installability.

**Comment by aidanheerdegen** [comment]
Moving the command line argument parsing etc in to `main()` has broken the (arguably) incorrect global scope of the project variable.
```~/.local/bin/ncimonitor -P v45
Traceback (most recent call last):
  File "/home/502/aph502/.local/bin/ncimonitor", line 11, in <module>
    load_entry_point('ncimonitor===dev', 'console_scripts', 'ncimonitor')()
  File "/home/502/aph502/.local/lib/python2.7/site-packages/ncimonitor/nci_monitor.py", line 334, in main
    plot_usage(db,year,quarter,plot_by_user,total_grant,users,args.pdf)
  File "/home/502/aph502/.local/lib/python2.7/site-packages/ncimonitor/nci_monitor.py", line 160, in plot_usage
    title = "Usage for Project {} on {} ({}.{})".format(project,system,year,quarter)
NameError: global name 'project' is not defined
```

**Comment by ScottWales** [comment]
```
ncimonitor -P w35 --showtotal
```
is now working for me

**Comment by aidanheerdegen** [comment]
Confirmed for me too.

**Pull request merged**
